++
Assembly code generated by MinCaml modified by Yuya Tanaka. 
Target machine: I8 version 1
THIS IS MAIN ENTRY POINT!
++
min_caml_start:
    lui      %r1  -1                       # !4
    li       %r1  -8                       # !4
    ++
    li 4294967288
    => lui %r1 0b11111111111
       li  %r1 0b111111111111111111000
    ++
    addi     %r2  %zero  30                # !4
    sw       %r1  %sp  0                   # !4
    movz     %r1  %r2  %zero               # !4
    sw       %ra  %sp  -1                  # !4
    addi     %sp  %sp  -2                  # !4
    jal      ~fib.12                       # !4
    addi     %sp  %sp  2                   # !4
    lw       %ra  %sp  -1                  # !4
    lw       %r2  %sp  0                   # !4
    sw       %r1  %r2  0                   # !4
    j        ~inf_loop                     # !0
inf_loop:
    j        ~inf_loop                     # !0

++
These are function definitions.
++
fib.12:
    addi     %r2  %zero  1                 # !2
    blt      %r2  %r1  blt_then.29         # !2
    jr       %ra                           # !2
blt_then.29:
    addi     %r2  %r1  -1                  # !3
    sw       %r1  %sp  0                   # !3
    movz     %r1  %r2  %zero               # !3
    sw       %ra  %sp  -1                  # !3
    addi     %sp  %sp  -2                  # !3
    jal      ~fib.12                       # !3
    addi     %sp  %sp  2                   # !3
    lw       %ra  %sp  -1                  # !3
    lw       %r2  %sp  0                   # !3
    addi     %r2  %r2  -2                  # !3
    sw       %r1  %sp  -1                  # !3
    movz     %r1  %r2  %zero               # !3
    sw       %ra  %sp  -2                  # !3
    addi     %sp  %sp  -3                  # !3
    jal      ~fib.12                       # !3
    addi     %sp  %sp  3                   # !3
    lw       %ra  %sp  -2                  # !3
    lw       %r2  %sp  -1                  # !3
    add      %r1  %r2  %r1                 # !3
    jr       %ra                           # !3
