++
Assembly code generated by MinCaml modified by Yuya Tanaka. 
Target machine: I8 version 1
THIS IS MAIN ENTRY POINT!
++
min_caml_start:
    sw       %ra  %sp  0                   # !2
    addi     %sp  %sp  1                   # !2
    jal      ~min_caml_f                   # !2
    addi     %sp  %sp  -1                  # !2
    lw       %ra  %sp  0                   # !2
    sra      %r1  %r1  4                   # !3
    addi     %r1  %r1  -8                  # !3
    sw       %ra  %sp  0                   # !3
    addi     %sp  %sp  1                   # !3
    jal      ~min_caml_g                   # !3
    addi     %sp  %sp  -1                  # !3
    lw       %ra  %sp  0                   # !3
    j        ~inf_loop                     # !0
inf_loop:
    j        ~inf_loop                     # !0

++
These are function definitions.
++
