++
Assembly code generated by MinCaml modified by Yuya Tanaka. 
Target machine: I8 version 1
THIS IS MAIN ENTRY POINT!
++
min_caml_start:
    addi     %r1  %zero  10             # !2
    sw       %r1  %sp  0                # !2
    sw       %ra  %sp  1                # !2
    addi     %sp  %sp  2                # !2
    jal      ~f.9                       # !2
    addi     %sp  %sp  -2               # !2
    lw       %ra  %sp  1                # !2
    movz     %r2  %hp  %zero            # !3
    addi     %hp  %hp  -2               # !3
    setl     %r3  ~g.12                 # !3
    sw       %r3  %r2  0                # !3
    sw       %r1  %r2  -1               # !3
    movz     %r27  %hp  %zero           # !4
    addi     %hp  %hp  -2               # !4
    setl     %r1  ~h.14                 # !4
    sw       %r1  %r27  0               # !4
    sw       %r2  %r27  -1              # !4
    addi     %r1  %zero  5              # !5
    sw       %r2  %sp  1                # !5
    sw       %ra  %sp  2                # !5
    addi     %sp  %sp  3                # !5
    lw       %r28  %r27  0              # !5
    jalr     %r28                       # !5
    addi     %sp  %sp  -3               # !5
    lw       %ra  %sp  2                # !5
    lw       %r2  %sp  0                # !5
    lw       %r27  %sp  1               # !5
    sw       %r1  %sp  2                # !5
    movz     %r1  %r2  %zero            # !5
    sw       %ra  %sp  3                # !5
    addi     %sp  %sp  4                # !5
    lw       %r28  %r27  0              # !5
    jalr     %r28                       # !5
    addi     %sp  %sp  -4               # !5
    lw       %ra  %sp  3                # !5
    lw       %r2  %sp  2                # !5
    add      %r1  %r2  %r1              # !5
    sw       %ra  %sp  3                # !5
    addi     %sp  %sp  4                # !5
    jal      ~min_caml_print_int        # !5
    addi     %sp  %sp  -4               # !5
    lw       %ra  %sp  3                # !5
    j        ~inf_loop                  # !0
inf_loop:
    j        ~inf_loop                  # !0

++
These are function definitions.
++
f.9:
    addi     %r1  %r1  1                # !1
    jr       %ra                        # !1
g.12:
    lw       %r2  %r27  1               # !3
    add      %r1  %r2  %r1              # !3
    jr       %ra                        # !3
h.14:
    lw       %r2  %r27  1               # !4
    sw       %r2  %sp  0                # !4
    sw       %ra  %sp  1                # !4
    addi     %sp  %sp  2                # !4
    jal      ~f.9                       # !4
    addi     %sp  %sp  -2               # !4
    lw       %ra  %sp  1                # !4
    lw       %r27  %sp  0               # !4
    lw       %r28  %r27  0              # !4
    jr       %r28                       # !4
