++
Assembly code generated by MinCaml modified by Yuya Tanaka. 
Target machine: I8 version 1
THIS IS MAIN ENTRY POINT!
++
min_caml_start:
    sw       %ra  %sp  0                # !1
    addi     %sp  %sp  1                # !1
    jal      ~min_caml_f                # !1
    addi     %sp  %sp  -1               # !1
    lw       %ra  %sp  0                # !1
    lw       %r2  %r1  1                # !1
    lw       %r1  %r1  0                # !1
    add      %r1  %r1  %r2              # !4
    sw       %ra  %sp  0                # !4
    addi     %sp  %sp  1                # !4
    jal      ~min_caml_print_int        # !4
    addi     %sp  %sp  -1               # !4
    lw       %ra  %sp  0                # !4
    sw       %ra  %sp  0                # !7
    addi     %sp  %sp  1                # !7
    jal      ~g.15                      # !7
    addi     %sp  %sp  -1               # !7
    lw       %ra  %sp  0                # !7
    sw       %ra  %sp  0                # !8
    addi     %sp  %sp  1                # !8
    jal      ~min_caml_h                # !8
    addi     %sp  %sp  -1               # !8
    lw       %ra  %sp  0                # !8
    sw       %ra  %sp  0                # !9
    addi     %sp  %sp  1                # !9
    jal      ~min_caml_print_int        # !9
    addi     %sp  %sp  -1               # !9
    lw       %ra  %sp  0                # !9
    j        ~inf_loop                  # !0
inf_loop:
    j        ~inf_loop                  # !0

++
These are function definitions.
++
g.15:
    addi     %r1  %zero  1              # !6
    addi     %r2  %zero  2              # !6
    addi     %r3  %zero  3              # !6
    movz     %r4  %hp  %zero            # !6
    addi     %hp  %hp  -2               # !6
    sw       %r3  %r4  -1               # !6
    sw       %r2  %r4  0                # !6
    movz     %r2  %r4  %zero            # !6
    movz     %r3  %hp  %zero            # !6
    addi     %hp  %hp  -2               # !6
    sw       %r2  %r3  -1               # !6
    sw       %r1  %r3  0                # !6
    movz     %r1  %r3  %zero            # !6
    jr       %ra                        # !6
