++
Assembly code generated by MinCaml modified by Yuya Tanaka. 
Target machine: I8 version 1
THIS IS MAIN ENTRY POINT!
++
min_caml_start:
    addi     %r1  %zero  5                 # !70
    addi     %r2  %zero  0                 # !70
    sw       %r2  %sp  0                   # !70
    sw       %ra  %sp  -1                  # !70
    addi     %sp  %sp  -2                  # !70
    jal      ~min_caml_create_array        # !70
    addi     %sp  %sp  2                   # !70
    lw       %ra  %sp  -1                  # !70
    addi     %r2  %zero  2                 # !72
    sw       %r2  %r1  0                   # !72
    lw       %r2  %r1  0                   # !73
    lw       %r1  %r1  0                   # !73
    beq      %r2  %r1  beq_then.203        # !73
    addi     %r1  %zero  -2                # !73
    lw       %r2  %sp  0                   # !73
    sw       %r2  %r1  0                   # !73
    j        ~beq_cont.204                 # !73
beq_then.203:
    addi     %r1  %zero  -2                # !73
    addi     %r2  %zero  1                 # !73
    sw       %r2  %r1  0                   # !73
beq_cont.204:
    j        ~inf_loop                     # !0
inf_loop:
    j        ~inf_loop                     # !0

++
These are function definitions.
++
++
Array routines for the i8v1 architecture.
++
min_caml_create_array:
    sw       %ra  %sp  0
    sw       %r1  %sp  -1
    addi     %sp  %sp  -2
    jal      ~create_array_loop
    addi     %sp  %sp  2
    lw       %ra  %sp  0
    lw       %r2  %sp  -1
    movz     %r1  %hp  %zero
    add      %hp  %hp  %r2
    jr       %ra
create_array_loop:
    blt      %zero  %r1  create_array_loop_blt_then
    jr       %ra
create_array_loop_blt_then:
    addi     %r1  %r1  -1
    swv      %r2  %hp  %r1
    j        ~create_array_loop

min_caml_create_float_array:
    sw       %ra  %sp  0
    sw       %r1  %sp  -1
    addi     %sp  %sp  -2
    jal      ~create_float_array_loop
    addi     %sp  %sp  2
    lw       %ra  %sp  0
    lw       %r2  %sp  -1
    movz     %r1  %hp  %zero
    add      %hp  %hp  %r2
    jr       %ra
create_float_array_loop:
    blt      %zero  %r1  create_float_array_loop_blt_then
    jr       %ra
create_float_array_loop_blt_then:
    addi     %r1  %r1  -1
    fswv     %f0  %hp  %r1
    j        ~create_float_array_loop