++
Assembly code generated by MinCaml modified by Yuya Tanaka. 
Target machine: I8 version 1
THIS IS MAIN ENTRY POINT!
++
min_caml_start:
    addi     %r1  %zero  5                 # !1
    addi     %r2  %zero  0                 # !1
    sw       %r2  %sp  0                   # !1
    sw       %ra  %sp  -1                  # !1
    addi     %sp  %sp  -2                  # !1
    jal      ~min_caml_create_array        # !1
    addi     %sp  %sp  2                   # !1
    lw       %ra  %sp  -1                  # !1
    addi     %r2  %zero  2                 # !3
    sw       %r2  %r1  0                   # !3
    lw       %r2  %r1  0                   # !4
    lw       %r1  %r1  0                   # !4
    beq      %r2  %r1  beq_then.27         # !4
    lw       %r1  %sp  0                   # !4
    sw       %ra  %sp  -1                  # !4
    addi     %sp  %sp  -2                  # !4
    jal      ~min_caml_print_int           # !4
    addi     %sp  %sp  2                   # !4
    lw       %ra  %sp  -1                  # !4
    j        ~beq_cont.28                  # !4
beq_then.27:
    addi     %r1  %zero  1                 # !4
    sw       %ra  %sp  -1                  # !4
    addi     %sp  %sp  -2                  # !4
    jal      ~min_caml_print_int           # !4
    addi     %sp  %sp  2                   # !4
    lw       %ra  %sp  -1                  # !4
beq_cont.28:
    j        ~inf_loop                     # !0
inf_loop:
    j        ~inf_loop                     # !0

++
These are function definitions.
++
++
Array routines for the i8v1 architecture.
++
min_caml_create_array:
    sw       %ra  %sp  0
    sw       %r1  %sp  -1
    addi     %sp  %sp  -2
    jal      ~create_array_loop
    addi     %sp  %sp  2
    lw       %ra  %sp  0
    lw       %r2  %sp  -1
    movz     %r1  %hp  %zero
    add      %hp  %hp  %r2
    jr       %ra
create_array_loop:
    blt      %zero  %r1  create_array_loop_blt_then
    jr       %ra
create_array_loop_blt_then:
    addi     %r1  %r1  -1
    swv      %r2  %hp  %r1
    j        ~create_array_loop

min_caml_create_float_array:
    sw       %ra  %sp  0
    sw       %r1  %sp  -1
    addi     %sp  %sp  -2
    jal      ~create_float_array_loop
    addi     %sp  %sp  2
    lw       %ra  %sp  0
    lw       %r2  %sp  -1
    movz     %r1  %hp  %zero
    add      %hp  %hp  %r2
    jr       %ra
create_float_array_loop:
    blt      %zero  %r1  create_float_array_loop_blt_then
    jr       %ra
create_float_array_loop_blt_then:
    addi     %r1  %r1  -1
    fswv     %f0  %hp  %r1
    j        ~create_float_array_loop
