++
Assembly code generated by MinCaml modified by Yuya Tanaka. 
Target machine: I8 version 1
THIS IS MAIN ENTRY POINT!
++
min_caml_start:
    addi     %r1  %zero  1              # !1
    addi     %r2  %zero  2              # !1
    addi     %r3  %zero  3              # !1
    movz     %r4  %hp  %zero            # !1
    addi     %hp  %hp  -3               # !1
    sw       %r3  %r4  -2               # !1
    sw       %r2  %r4  -1               # !1
    sw       %r1  %r4  0                # !1
    movz     %r2  %r4  %zero            # !1
    sw       %ra  %sp  0                # !1
    addi     %sp  %sp  1                # !1
    jal      ~min_caml_create_array     # !1
    addi     %sp  %sp  -1               # !1
    lw       %ra  %sp  0                # !1
    lw       %r1  %r1  0                # !3
    lw       %r2  %r1  2                # !3
    lw       %r3  %r1  1                # !3
    lw       %r1  %r1  0                # !3
    sw       %r2  %sp  0                # !6
    sw       %r3  %sp  1                # !6
    sw       %ra  %sp  2                # !6
    addi     %sp  %sp  3                # !6
    jal      ~min_caml_print_int        # !6
    addi     %sp  %sp  -3               # !6
    lw       %ra  %sp  2                # !6
    lw       %r1  %sp  1                # !6
    sw       %ra  %sp  2                # !6
    addi     %sp  %sp  3                # !6
    jal      ~min_caml_print_int        # !6
    addi     %sp  %sp  -3               # !6
    lw       %ra  %sp  2                # !6
    lw       %r1  %sp  0                # !6
    sw       %ra  %sp  2                # !6
    addi     %sp  %sp  3                # !6
    jal      ~min_caml_print_int        # !6
    addi     %sp  %sp  -3               # !6
    lw       %ra  %sp  2                # !6
    sw       %ra  %sp  2                # !6
    addi     %sp  %sp  3                # !6
    jal      ~min_caml_print_newline    # !6
    addi     %sp  %sp  -3               # !6
    lw       %ra  %sp  2                # !6
    j        ~inf_loop                  # !0
inf_loop:
    j        ~inf_loop                  # !0

++
These are function definitions.
++
