++
Assembly code generated by MinCaml modified by Yuya Tanaka. 
Target machine: I8 version 1
THIS IS MAIN ENTRY POINT!
++
min_caml_start:
    flui %f0 514                           # !3
    fli %f0 593883                         # !3
    ++
    fli 3.141593
    => flui %f0 0b01000000010
       fli  %f0 0b010010000111111011011
    ++
    flui %f1 518                           # !4
    fli %f1 593883                         # !4
    ++
    fli 6.283185
    => flui %f1 0b01000000110
       fli  %f1 0b010010000111111011011
    ++
    movz %r27 %hp %zero                    # !11
    addi %hp %hp -3                        # !11
    setl %r1 ~reduce_to_pi.16              # !11
    sw %r1 %r27 0                          # !11
    fsw %f1 %r27 -2                        # !11
    fsw %f0 %r27 -1                        # !11
    flui %f0 520                           # !18
    fli %f0 -603164                        # !18
    ++
    fli 9.424778
    => flui %f0 0b01000001000
       fli  %f0 0b101101100101111100100
    ++
    sw %ra %sp 0                           # !18
    addi %sp %sp 1                         # !18
    lw %r28 %r27 0                         # !18
    jalr %r28                              # !18
    addi %sp %sp -1                        # !18
    lw %ra %sp 0                           # !18
    sw %ra %sp 0                           # !18
    addi %sp %sp 1                         # !18
    jal ~min_caml_print                    # !18
    addi %sp %sp -1                        # !18
    lw %ra %sp 0                           # !18
    j ~inf_loop                            # !0
inf_loop:
    j ~inf_loop                            # !0

++
These are function definitions.
++
fmod.13:
    fdiv %f2 %f0 %f1                       # !8
    floor %f2 %f2                          # !8
    fmul %f1 %f2 %f1                       # !8
    fsub %f0 %f0 %f1                       # !8
    jr %ra                                 # !8
reduce_to_pi.16:
    flw %f1 %r27 2                         # !11
    flw %f2 %r27 1                         # !11
    fsw %f1 %sp 0                          # !12
    fsw %f2 %sp 1                          # !12
    sw %ra %sp 2                           # !12
    addi %sp %sp 3                         # !12
    jal ~fmod.13                           # !12
    addi %sp %sp -3                        # !12
    lw %ra %sp 2                           # !12
    flw %f1 %sp 1                          # !13
    fblt %f1 %f0 fblt_then.35              # !13
    flui %f1 -510                          # !14
    fli %f1 593883                         # !14
    ++
    fli -3.141593
    => flui %f1 0b11000000010
       fli  %f1 0b010010000111111011011
    ++
    fblt %f0 %f1 fblt_then.36              # !14
    jr %ra                                 # !15
fblt_then.36:
    flw %f1 %sp 0                          # !14
    fadd %f0 %f0 %f1                       # !14
    jr %ra                                 # !14
fblt_then.35:
    flw %f1 %sp 0                          # !13
    fsub %f0 %f0 %f1                       # !13
    jr %ra                                 # !13
