(executable
 (name main)
 (package min-caml)
 (public_name mincaml)
 (foreign_stubs (language c) (names float))
 (libraries unix))

(ocamllex myLexer)
(ocamlyacc myParser)

(copy_files
 (files x86/*)
 (enabled_if (or (= %{profile} x86) (= %{profile} dev) (= %{profile} release)))
 (alias to_x86))

(copy_files
 (files PowerPC/*)
 (enabled_if (= %{profile} ppc))
 (alias to_ppc))

(copy_files
 (files SPARC/*)
 (enabled_if (= %{profile} sparc))
 (alias to_sparc))

(copy_files
 (files i8v1/*)
 (enabled_if (= %{profile} i8v1))
 (alias to_i8v1))

(env
 (dev
  (flags (:standard -warn-error -a))))
