++
Assembly code generated by MinCaml modified by Yuya Tanaka. 
Target machine: I8 version 1
THIS IS MAIN ENTRY POINT!
++
min_caml_start:
    li       %r1  -8                       # !74
    lui      %r1  -1                       # !74
    ++
    li 4294967288
    => li  %r1 0b111111111111111111000
       lui %r1 0b11111111111
    ++
    fli      %f0  0                        # !74
    flui     %f0  521                      # !74
    ++
    fli 10.000000
    => fli  %f0 0b000000000000000000000
       flui %f0 0b01000001001
    ++
    sw       %r1  %sp  0                   # !74
    sw       %ra  %sp  -1                  # !74
    addi     %sp  %sp  -2                  # !74
    jal      ~fib.89                       # !74
    addi     %sp  %sp  2                   # !74
    lw       %ra  %sp  -1                  # !74
    lw       %r1  %sp  0                   # !74
    fsw      %f0  %r1  0                   # !74
    j        ~inf_loop                     # !0
inf_loop:
    j        ~inf_loop                     # !0

++
These are function definitions.
++
fib.89:
    fli      %f1  0                        # !71
    flui     %f1  512                      # !71
    ++
    fli 2.000000
    => fli  %f1 0b000000000000000000000
       flui %f1 0b01000000000
    ++
    fblt     %f0  %f1  fblt_then.198       # !71
    fli      %f2  0                        # !72
    flui     %f2  508                      # !72
    ++
    fli 1.000000
    => fli  %f2 0b000000000000000000000
       flui %f2 0b00111111100
    ++
    fsub     %f2  %f0  %f2                 # !72
    fsw      %f1  %sp  0                   # !72
    fsw      %f0  %sp  -1                  # !72
    fmovz    %f0  %f2  %zero               # !72
    sw       %ra  %sp  -2                  # !72
    addi     %sp  %sp  -3                  # !72
    jal      ~fib.89                       # !72
    addi     %sp  %sp  3                   # !72
    lw       %ra  %sp  -2                  # !72
    flw      %f1  %sp  0                   # !72
    flw      %f2  %sp  -1                  # !72
    fsub     %f1  %f2  %f1                 # !72
    fsw      %f0  %sp  -2                  # !72
    fmovz    %f0  %f1  %zero               # !72
    sw       %ra  %sp  -3                  # !72
    addi     %sp  %sp  -4                  # !72
    jal      ~fib.89                       # !72
    addi     %sp  %sp  4                   # !72
    lw       %ra  %sp  -3                  # !72
    flw      %f1  %sp  -2                  # !72
    fadd     %f0  %f1  %f0                 # !72
    jr       %ra                           # !72
fblt_then.198:
    jr       %ra                           # !71
++
Array routines for the i8v1 architecture.
++
min_caml_create_array:
    sw       %ra  %sp  0
    sw       %r1  %sp  -1
    addi     %sp  %sp  -2
    jal      ~create_array_loop
    addi     %sp  %sp  2
    lw       %ra  %sp  0
    lw       %r2  %sp  -1
    movz     %r1  %hp  %zero
    add      %hp  %hp  %r2
    jr       %ra
create_array_loop:
    blt      %zero  %r1  create_array_loop_blt_then
    jr       %ra
create_array_loop_blt_then:
    addi     %r1  %r1  -1
    swv      %r2  %hp  %r1
    j        ~create_array_loop

min_caml_create_float_array:
    sw       %ra  %sp  0
    sw       %r1  %sp  -1
    addi     %sp  %sp  -2
    jal      ~create_float_array_loop
    addi     %sp  %sp  2
    lw       %ra  %sp  0
    lw       %r2  %sp  -1
    movz     %r1  %hp  %zero
    add      %hp  %hp  %r2
    jr       %ra
create_float_array_loop:
    blt      %zero  %r1  create_float_array_loop_blt_then
    jr       %ra
create_float_array_loop_blt_then:
    addi     %r1  %r1  -1
    fswv     %f0  %hp  %r1
    j        ~create_float_array_loop