++
Assembly code generated by MinCaml modified by Yuya Tanaka. 
Target machine: I8 version 1
THIS IS MAIN ENTRY POINT!
++
min_caml_start:
    addi     %r1  %zero  100               # !70
    addi     %r2  %zero  -1                # !70
    sw       %ra  %sp  0                   # !70
    addi     %sp  %sp  -1                  # !70
    jal      ~min_caml_create_array        # !70
    addi     %sp  %sp  1                   # !70
    lw       %ra  %sp  0                   # !70
    movz     %r27  %hp  %zero              # !71
    addi     %hp  %hp  2                   # !71
    setl     %r2  ~fib.104                 # !71
    sw       %r2  %r27  0                  # !71
    sw       %r1  %r27  1                  # !71
    li       %r1  -8                       # !80
    lui      %r1  -1                       # !80
    ++
    li 4294967288
    => li  %r1 0b111111111111111111000
       lui %r1 0b11111111111
    ++
    addi     %r2  %zero  50                # !80
    sw       %r1  %sp  0                   # !80
    movz     %r1  %r2  %zero               # !80
    sw       %ra  %sp  -1                  # !80
    addi     %sp  %sp  -2                  # !80
    lw       %r28  %r27  0                 # !80
    jalr     %r28                          # !80
    addi     %sp  %sp  2                   # !80
    lw       %ra  %sp  -1                  # !80
    lw       %r2  %sp  0                   # !80
    sw       %r1  %r2  0                   # !80
    j        ~inf_loop                     # !0
inf_loop:
    j        ~inf_loop                     # !0

++
These are function definitions.
++
fib.104:
    lw       %r2  %r27  1                  # !71
    addi     %r3  %zero  1                 # !72
    blt      %r3  %r1  blt_then.236        # !72
    jr       %ra                           # !72
blt_then.236:
    addi     %r3  %zero  100               # !73
    blt      %r1  %r3  blt_then.237        # !73
    addi     %r2  %r1  -1                  # !73
    sw       %r27  %sp  0                  # !73
    sw       %r1  %sp  -1                  # !73
    movz     %r1  %r2  %zero               # !73
    sw       %ra  %sp  -2                  # !73
    addi     %sp  %sp  -3                  # !73
    lw       %r28  %r27  0                 # !73
    jalr     %r28                          # !73
    addi     %sp  %sp  3                   # !73
    lw       %ra  %sp  -2                  # !73
    lw       %r2  %sp  -1                  # !73
    addi     %r2  %r2  -2                  # !73
    lw       %r27  %sp  0                  # !73
    sw       %r1  %sp  -2                  # !73
    movz     %r1  %r2  %zero               # !73
    sw       %ra  %sp  -3                  # !73
    addi     %sp  %sp  -4                  # !73
    lw       %r28  %r27  0                 # !73
    jalr     %r28                          # !73
    addi     %sp  %sp  4                   # !73
    lw       %ra  %sp  -3                  # !73
    lw       %r2  %sp  -2                  # !73
    add      %r1  %r2  %r1                 # !73
    jr       %ra                           # !73
blt_then.237:
    lwv      %r3  %r2  %r1                 # !74
    addi     %r4  %zero  -1                # !74
    beq      %r3  %r4  beq_then.238        # !74
    lwv      %r1  %r2  %r1                 # !78
    jr       %ra                           # !78
beq_then.238:
    addi     %r3  %r1  -1                  # !75
    sw       %r2  %sp  -3                  # !75
    sw       %r27  %sp  0                  # !75
    sw       %r1  %sp  -1                  # !75
    movz     %r1  %r3  %zero               # !75
    sw       %ra  %sp  -4                  # !75
    addi     %sp  %sp  -5                  # !75
    lw       %r28  %r27  0                 # !75
    jalr     %r28                          # !75
    addi     %sp  %sp  5                   # !75
    lw       %ra  %sp  -4                  # !75
    lw       %r2  %sp  -1                  # !75
    addi     %r3  %r2  -2                  # !75
    lw       %r27  %sp  0                  # !75
    sw       %r1  %sp  -4                  # !75
    movz     %r1  %r3  %zero               # !75
    sw       %ra  %sp  -5                  # !75
    addi     %sp  %sp  -6                  # !75
    lw       %r28  %r27  0                 # !75
    jalr     %r28                          # !75
    addi     %sp  %sp  6                   # !75
    lw       %ra  %sp  -5                  # !75
    lw       %r2  %sp  -4                  # !75
    add      %r1  %r2  %r1                 # !75
    lw       %r2  %sp  -1                  # !76
    lw       %r3  %sp  -3                  # !76
    swv      %r1  %r3  %r2                 # !76
    jr       %ra                           # !77
++
Array routines for the i8v1 architecture.
++
min_caml_create_array:
    sw       %ra  %sp  0
    sw       %r1  %sp  -1
    addi     %sp  %sp  -2
    jal      ~create_array_loop
    addi     %sp  %sp  2
    lw       %ra  %sp  0
    lw       %r2  %sp  -1
    movz     %r1  %hp  %zero
    add      %hp  %hp  %r2
    jr       %ra
create_array_loop:
    blt      %zero  %r1  create_array_loop_blt_then
    jr       %ra
create_array_loop_blt_then:
    addi     %r1  %r1  -1
    swv      %r2  %hp  %r1
    j        ~create_array_loop

min_caml_create_float_array:
    sw       %ra  %sp  0
    sw       %r1  %sp  -1
    addi     %sp  %sp  -2
    jal      ~create_float_array_loop
    addi     %sp  %sp  2
    lw       %ra  %sp  0
    lw       %r2  %sp  -1
    movz     %r1  %hp  %zero
    add      %hp  %hp  %r2
    jr       %ra
create_float_array_loop:
    blt      %zero  %r1  create_float_array_loop_blt_then
    jr       %ra
create_float_array_loop_blt_then:
    addi     %r1  %r1  -1
    fswv     %f0  %hp  %r1
    j        ~create_float_array_loop